// <auto-generated />
namespace UsedCarApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adcaruser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adcaruser));
        
        string IMigrationMetadata.Id
        {
            get { return "202106062106306_ad-car-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
