// <auto-generated />
namespace UsedCarApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adprice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adprice));
        
        string IMigrationMetadata.Id
        {
            get { return "202106080408340_ad-price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
